Repository Please-Hug/Please-Hug_BackEnd, pull requests merged in 2025-07, with the labels that each got.

#180 Feature/#178 미션 서비스 리팩토링
  src/main/java/org/example/hugmeexp/domain/mission/controller/ChallengeController.java
  src/main/java/org/example/hugmeexp/domain/mission/controller/MissionController.java
  src/main/java/org/example/hugmeexp/domain/mission/controller/SubmissionAdminController.java
  src/main/java/org/example/hugmeexp/domain/mission/controller/SubmissionController.java
  src/main/java/org/example/hugmeexp/domain/mission/service/MissionService.java
  src/main/java/org/example/hugmeexp/domain/mission/service/MissionServiceImpl.java
  src/main/java/org/example/hugmeexp/domain/mission/service/SubmissionService.java
  src/main/java/org/example/hugmeexp/domain/mission/service/SubmissionServiceImpl.java
  src/main/java/org/example/hugmeexp/domain/mission/service/UserMissionService.java
  src/main/java/org/example/hugmeexp/domain/mission/service/UserMissionServiceImpl.java
  src/test/java/org/example/hugmeexp/domain/mission/controller/ChallengeControllerTest.java
  src/test/java/org/example/hugmeexp/domain/mission/controller/MissionControllerTest.java
  src/test/java/org/example/hugmeexp/domain/mission/controller/SubmissionControllerTest.java
  src/test/java/org/example/hugmeexp/domain/mission/service/MissionServiceTest.java
  src/test/java/org/example/hugmeexp/domain/mission/service/SubmissionServiceTest.java
  src/test/java/org/example/hugmeexp/domain/mission/service/UserMissionServiceTest.java
Labels: 기능 개발, 성능 개선

#184 Feature/#182 미션 관련 권한 설정 및 테스트 코드
  src/main/java/org/example/hugmeexp/domain/mission/controller/ChallengeController.java
  src/main/java/org/example/hugmeexp/domain/mission/controller/MissionController.java
  src/main/java/org/example/hugmeexp/domain/mission/controller/SubmissionAdminController.java
  src/main/java/org/example/hugmeexp/domain/mission/controller/SubmissionController.java
  src/main/java/org/example/hugmeexp/domain/mission/dto/response/UserMissionStateLogResponse.java
  src/main/java/org/example/hugmeexp/domain/missionGroup/controller/MissionGroupController.java
  src/main/java/org/example/hugmeexp/domain/missionTask/controller/MissionTaskController.java
  src/main/java/org/example/hugmeexp/global/common/config/WebConfig.java
  src/main/java/org/example/hugmeexp/global/common/exception/ExceptionController.java
  src/test/java/org/example/hugmeexp/domain/mission/service/SubmissionServiceTest.java
  src/test/java/org/example/hugmeexp/domain/mission/service/UserMissionServiceTest.java
  src/test/java/org/example/hugmeexp/domain/mission/util/FileUploadUtilsTest.java
Labels: 기능 개발

#187 fix: 제품 이미지 업로드 경로 수정
  docker/init.sql
  src/main/java/org/example/hugmeexp/domain/shop/service/ProductAdminService.java
Labels: 버그

#188 칭찬하기 테스트 코드 작성
  src/main/java/org/example/hugmeexp/domain/praise/service/PraiseService.java
  src/test/java/org/example/hugmeexp/domain/praise/service/CommentEmojiReactionServiceTest.java
  src/test/java/org/example/hugmeexp/domain/praise/service/CommentServiceTest.java
  src/test/java/org/example/hugmeexp/domain/praise/service/PraiseServiceTest.java
  src/test/java/org/example/hugmeexp/global/auth/controller/LoginControllerTest.java
  src/test/java/org/example/hugmeexp/global/auth/controller/LogoutControllerTest.java
  src/test/java/org/example/hugmeexp/global/auth/controller/RefreshControllerTest.java
  src/test/java/org/example/hugmeexp/global/auth/controller/RegisterControllerTest.java
Labels: 기능 개발

#193 알림 기능 구현 - 칭찬 받았을 경우
  src/main/java/org/example/hugmeexp/domain/notification/controller/NotificationController.java
  src/main/java/org/example/hugmeexp/domain/notification/dto/NotificationResponseDTO.java
  src/main/java/org/example/hugmeexp/domain/notification/entity/Notification.java
  src/main/java/org/example/hugmeexp/domain/notification/enums/NotificationType.java
  src/main/java/org/example/hugmeexp/domain/notification/exception/ForbiddenNotificationAccessException.java
  src/main/java/org/example/hugmeexp/domain/notification/exception/NotificationNotFoundException.java
  src/main/java/org/example/hugmeexp/domain/notification/repository/NotificationRepository.java
  src/main/java/org/example/hugmeexp/domain/notification/service/NotificationService.java
  src/main/java/org/example/hugmeexp/domain/praise/service/PraiseService.java
  src/main/java/org/example/hugmeexp/global/common/sse/EmitterRepository.java
  src/main/java/org/example/hugmeexp/global/common/sse/SseController.java
  src/main/java/org/example/hugmeexp/global/common/sse/SseService.java
  src/test/java/org/example/hugmeexp/domain/praise/service/PraiseServiceTest.java
Labels: 기능 개발

#195 Feature/#194 미션 어드민 기능 관련 수정
  src/main/java/org/example/hugmeexp/domain/mission/service/MissionServiceImpl.java
  src/main/java/org/example/hugmeexp/domain/missionGroup/controller/MissionGroupController.java
  src/main/java/org/example/hugmeexp/domain/missionGroup/entity/MissionGroup.java
  src/main/java/org/example/hugmeexp/domain/missionGroup/service/MissionGroupService.java
  src/main/java/org/example/hugmeexp/domain/missionGroup/service/MissionGroupServiceImpl.java
  src/test/java/org/example/hugmeexp/domain/missionGroup/controller/MissionGroupControllerTest.java
  src/test/java/org/example/hugmeexp/domain/missionGroup/service/MissionGroupServiceTest.java
Labels: 기능 개발, 버그

#198 feat: 미션 및 미션 태스크에 팁 필드 추가
  src/main/java/org/example/hugmeexp/domain/mission/dto/request/MissionRequest.java
  src/main/java/org/example/hugmeexp/domain/mission/dto/response/MissionResponse.java
  src/main/java/org/example/hugmeexp/domain/mission/entity/Mission.java
  src/main/java/org/example/hugmeexp/domain/mission/service/MissionServiceImpl.java
  src/main/java/org/example/hugmeexp/domain/missionTask/dto/request/MissionTaskRequest.java
  src/main/java/org/example/hugmeexp/domain/missionTask/dto/response/MissionTaskResponse.java
  src/main/java/org/example/hugmeexp/domain/missionTask/entity/MissionTask.java
  src/main/java/org/example/hugmeexp/domain/missionTask/service/MissionTaskServiceImpl.java
  src/test/java/org/example/hugmeexp/domain/mission/service/MissionServiceTest.java
Labels: 기능 개발

#200 알림 칭찬하기 기능 추가
  src/main/java/org/example/hugmeexp/domain/notification/controller/NotificationController.java
  src/main/java/org/example/hugmeexp/domain/notification/dto/NotificationResponseDTO.java
  src/main/java/org/example/hugmeexp/domain/notification/entity/Notification.java
  src/main/java/org/example/hugmeexp/domain/notification/service/NotificationService.java
  src/main/java/org/example/hugmeexp/domain/praise/service/PraiseService.java
  src/main/java/org/example/hugmeexp/global/common/sse/SseController.java
  src/main/java/org/example/hugmeexp/global/infra/auth/jwt/JwtAuthenticationFilter.java
Labels: 기능 개발

#210 알림 배움일기 기능 구현
  src/main/java/org/example/hugmeexp/domain/notification/dto/NotificationDeleteDTO.java
  src/main/java/org/example/hugmeexp/domain/notification/repository/NotificationRepository.java
  src/main/java/org/example/hugmeexp/domain/notification/service/NotificationService.java
  src/main/java/org/example/hugmeexp/domain/studydiary/repository/StudyDiaryCommentRepository.java
  src/main/java/org/example/hugmeexp/domain/studydiary/service/StudyDiaryService.java
  src/main/java/org/example/hugmeexp/global/common/sse/SseService.java
Labels: 기능 개발

#212 Feature/#211 유저 랭킹 구현
  src/main/java/org/example/hugmeexp/domain/user/controller/UserInfoController.java
  src/main/java/org/example/hugmeexp/domain/user/dto/response/UserRankResponse.java
  src/main/java/org/example/hugmeexp/domain/user/repository/UserRepository.java
  src/main/java/org/example/hugmeexp/domain/user/service/UserService.java
Labels: 기능 개발

#214 feat: 미션 및 유저 미션 그룹의 일대다 관계 설정
  src/main/java/org/example/hugmeexp/domain/mission/entity/Mission.java
  src/main/java/org/example/hugmeexp/domain/mission/entity/UserMission.java
  src/main/java/org/example/hugmeexp/domain/missionGroup/entity/MissionGroup.java
  src/main/java/org/example/hugmeexp/domain/missionGroup/entity/UserMissionGroup.java
  src/main/java/org/example/hugmeexp/domain/user/dto/response/UserRankResponse.java
  src/main/java/org/example/hugmeexp/domain/user/entity/User.java
  src/main/java/org/example/hugmeexp/domain/user/repository/UserRepository.java
Labels: 기능 개발, 버그, 성능 개선

#216 관리자 도메인에서 유저 정보 변경을 위해 유저 도메인 변경
  src/main/java/org/example/hugmeexp/domain/admin/controller/AdminUserController.java
  src/main/java/org/example/hugmeexp/domain/admin/mapper/AdminUserResponseMapper.java
  src/main/java/org/example/hugmeexp/domain/user/dto/request/UserUpdateRequest.java
  src/main/java/org/example/hugmeexp/domain/user/dto/response/UserInfoResponse.java
  src/main/java/org/example/hugmeexp/domain/user/entity/User.java
  src/main/java/org/example/hugmeexp/domain/user/mapper/UserResponseMapper.java
  src/main/java/org/example/hugmeexp/domain/user/service/UserService.java
Labels: 기능 개발

#220 Feature/#215 미션 그룹 성능 향상
  src/main/java/org/example/hugmeexp/domain/mission/dto/response/UserMissionResponse.java
  src/main/java/org/example/hugmeexp/domain/mission/repository/UserMissionRepository.java
  src/main/java/org/example/hugmeexp/domain/mission/service/MissionServiceImpl.java
  src/main/java/org/example/hugmeexp/domain/mission/service/UserMissionServiceImpl.java
  src/main/java/org/example/hugmeexp/domain/missionGroup/controller/MissionGroupController.java
  src/main/java/org/example/hugmeexp/domain/missionGroup/dto/response/MissionGroupResponse.java
  src/main/java/org/example/hugmeexp/domain/missionGroup/dto/response/UserMissionGroupResponse.java
  src/main/java/org/example/hugmeexp/domain/missionGroup/mapper/UserMissionGroupMapper.java
  src/main/java/org/example/hugmeexp/domain/missionGroup/repository/MissionGroupRepository.java
  src/main/java/org/example/hugmeexp/domain/missionGroup/repository/UserMissionGroupRepository.java
  src/main/java/org/example/hugmeexp/domain/missionGroup/service/MissionGroupService.java
  src/main/java/org/example/hugmeexp/domain/missionGroup/service/MissionGroupServiceImpl.java
  src/main/java/org/example/hugmeexp/domain/user/dto/response/UserProfileResponse.java
  src/main/java/org/example/hugmeexp/global/common/config/CacheConfig.java
  src/main/java/org/example/hugmeexp/global/common/config/RedisConfig.java
  src/main/java/org/example/hugmeexp/global/common/service/CacheService.java
  src/main/java/org/example/hugmeexp/global/infra/auth/jwt/JwtTokenProvider.java
  src/main/java/org/example/hugmeexp/global/infra/auth/service/RedisSessionService.java
  src/main/java/org/example/hugmeexp/global/infra/auth/service/TokenService.java
  src/test/java/org/example/hugmeexp/domain/mission/service/MissionServiceTest.java
  src/test/java/org/example/hugmeexp/domain/mission/service/UserMissionServiceTest.java
  src/test/java/org/example/hugmeexp/domain/missionGroup/controller/MissionGroupControllerTest.java
  src/test/java/org/example/hugmeexp/domain/missionGroup/service/MissionGroupServiceTest.java
Labels: 성능 개선

#231 북마크 도메인 성능개선
  src/main/java/org/example/hugmeexp/domain/bookmark/service/BookmarkService.java
Labels: 성능 개선

#233 북마크: 테스트 코드 작성&레디스 캐시 안정성 강화
  src/main/java/org/example/hugmeexp/domain/bookmark/controller/BookmarkController.java
  src/main/java/org/example/hugmeexp/domain/bookmark/dto/request/BookmarkRequest.java
  src/main/java/org/example/hugmeexp/domain/bookmark/dto/response/BookmarkResponse.java
  src/main/java/org/example/hugmeexp/domain/bookmark/service/BookmarkService.java
  src/test/java/org/example/hugmeexp/domain/bookmark/controller/BookmarkControllerTest.java
  src/test/java/org/example/hugmeexp/domain/bookmark/service/BookmarkServiceTest.java
Labels: 기능 개발

#230 알림 테스트코드, swagger 추가
  src/main/java/org/example/hugmeexp/domain/notification/controller/NotificationController.java
  src/test/java/org/example/hugmeexp/domain/notification/service/NotificationServiceTest.java
Labels: 기능 개발
