Repository Please-Hug/Please-Hug_BackEnd, pull requests merged in 2025-06, with the labels that each got.

#39 Feature/#36 미션 그룹 리팩토링
  src/main/java/org/example/hugmeexp/domain/mission/controller/MissionGroupController.java
  src/main/java/org/example/hugmeexp/domain/mission/dto/MissionGroupRequest.java
  src/main/java/org/example/hugmeexp/domain/mission/dto/MissionGroupUpdateRequest.java
  src/main/java/org/example/hugmeexp/domain/mission/entity/MissionGroup.java
  src/main/java/org/example/hugmeexp/domain/mission/exception/MissionGroupNotFoundException.java
  src/main/java/org/example/hugmeexp/domain/mission/mapper/MissionGroupMapper.java
  src/main/java/org/example/hugmeexp/domain/mission/service/MissionGroupService.java
  src/main/java/org/example/hugmeexp/domain/missionGroup/controller/MissionGroupController.java
  src/main/java/org/example/hugmeexp/domain/missionGroup/dto/request/MissionGroupRequest.java
  src/main/java/org/example/hugmeexp/domain/missionGroup/dto/response/MissionGroupResponse.java
  src/main/java/org/example/hugmeexp/domain/missionGroup/entity/MissionGroup.java
  src/main/java/org/example/hugmeexp/domain/missionGroup/exception/MissionGroupNotFoundException.java
  src/main/java/org/example/hugmeexp/domain/missionGroup/exception/TeacherNotFoundException.java
  src/main/java/org/example/hugmeexp/domain/missionGroup/mapper/MissionGroupMapper.java
  src/main/java/org/example/hugmeexp/domain/missionGroup/repository/MissionGroupRepository.java
  src/main/java/org/example/hugmeexp/domain/missionGroup/service/MissionGroupService.java
  src/main/java/org/example/hugmeexp/domain/missionGroup/service/MissionGroupServiceImpl.java
  src/main/java/org/example/hugmeexp/global/exception/GlobalExceptionHandler.java
  src/test/java/org/example/hugmeexp/domain/missionGroup/controller/MissionGroupControllerTest.java
  src/test/java/org/example/hugmeexp/domain/missionGroup/service/MissionGroupServiceTest.java
Labels: 기능 개발

#44 Feature/praise 생성/조회
  src/main/java/org/example/hugmeexp/domain/praise/controller/PraiseController.java
  src/main/java/org/example/hugmeexp/domain/praise/dto/PraiseRequestDTO.java
  src/main/java/org/example/hugmeexp/domain/praise/dto/PraiseResponseDTO.java
  src/main/java/org/example/hugmeexp/domain/praise/entity/CommentEmojiReaction.java
  src/main/java/org/example/hugmeexp/domain/praise/entity/Praise.java
  src/main/java/org/example/hugmeexp/domain/praise/entity/PraiseComment.java
  src/main/java/org/example/hugmeexp/domain/praise/entity/PraiseEmojiReaction.java
  src/main/java/org/example/hugmeexp/domain/praise/enums/PraiseType.java
  src/main/java/org/example/hugmeexp/domain/praise/exception/UserNotFoundInPraiseException.java
  src/main/java/org/example/hugmeexp/domain/praise/mapper/PraiseMapper.java
  src/main/java/org/example/hugmeexp/domain/praise/repository/CommentEmojiReactionRepository.java
  src/main/java/org/example/hugmeexp/domain/praise/repository/CommentRepository.java
  src/main/java/org/example/hugmeexp/domain/praise/repository/PraiseEmojiReactionRepository.java
  src/main/java/org/example/hugmeexp/domain/praise/repository/PraiseRepository.java
  src/main/java/org/example/hugmeexp/domain/praise/service/PraiseService.java
  src/main/java/org/example/hugmeexp/global/common/repository/UserRepository.java
  src/main/java/org/example/hugmeexp/global/security/config/SecurityConfig.java
Labels: 기능 개발

#50 날짜 조회 / ME / keyword 조건 기능 구현
  src/main/java/org/example/hugmeexp/domain/praise/controller/PraiseController.java
  src/main/java/org/example/hugmeexp/domain/praise/dto/PraiseRequestDTO.java
  src/main/java/org/example/hugmeexp/domain/praise/repository/PraiseRepository.java
  src/main/java/org/example/hugmeexp/domain/praise/service/PraiseService.java
Labels: 기능 개발

#72 나를 최근에 칭찬한 유저
  src/main/java/org/example/hugmeexp/domain/praise/controller/PraiseController.java
  src/main/java/org/example/hugmeexp/domain/praise/dto/PraiseSearchRequestDTO.java
  src/main/java/org/example/hugmeexp/domain/praise/repository/PraiseRepository.java
  src/main/java/org/example/hugmeexp/domain/praise/service/PraiseService.java
Labels: 기능 개발

#76 Feature/#75 user profile response bugfix
  src/main/java/org/example/hugmeexp/domain/mission/dto/response/UserMissionResponse.java
  src/main/java/org/example/hugmeexp/domain/mission/mapper/MissionMapper.java
  src/main/java/org/example/hugmeexp/domain/mission/mapper/UserMissionMapper.java
  src/main/java/org/example/hugmeexp/domain/missionGroup/dto/response/MissionGroupResponse.java
  src/main/java/org/example/hugmeexp/domain/missionGroup/dto/response/UserMissionGroupResponse.java
  src/main/java/org/example/hugmeexp/domain/missionGroup/mapper/MissionGroupMapper.java
  src/main/java/org/example/hugmeexp/domain/praise/dto/RecentPraiseSenderResponseDTO.java
  src/main/java/org/example/hugmeexp/domain/user/dto/response/UserProfileResponse.java
  src/main/java/org/example/hugmeexp/domain/user/mapper/ProfileImageMapper.java
  src/test/java/org/example/hugmeexp/domain/missionGroup/controller/MissionGroupControllerTest.java
  src/test/java/org/example/hugmeexp/domain/missionGroup/service/MissionGroupServiceTest.java
Labels: 버그

#82 칭찬 게시물 세부 조회 기능
  src/main/java/org/example/hugmeexp/domain/praise/controller/PraiseController.java
  src/main/java/org/example/hugmeexp/domain/praise/dto/CommentResponseDTO.java
  src/main/java/org/example/hugmeexp/domain/praise/dto/PraiseDetailResponseDTO.java
  src/main/java/org/example/hugmeexp/domain/praise/entity/CommentEmojiReaction.java
  src/main/java/org/example/hugmeexp/domain/praise/exception/PraiseNotFoundException.java
  src/main/java/org/example/hugmeexp/domain/praise/repository/CommentEmojiReactionRepository.java
  src/main/java/org/example/hugmeexp/domain/praise/repository/CommentRepository.java
  src/main/java/org/example/hugmeexp/domain/praise/repository/PraiseEmojiReactionRepository.java
  src/main/java/org/example/hugmeexp/domain/praise/repository/PraiseReceiverRepository.java
  src/main/java/org/example/hugmeexp/domain/praise/service/PraiseService.java
Labels: 기능 개발

#86 칭찬 댓글 생성
  src/main/java/org/example/hugmeexp/domain/praise/controller/CommentController.java
  src/main/java/org/example/hugmeexp/domain/praise/dto/CommentRequestDTO.java
  src/main/java/org/example/hugmeexp/domain/praise/entity/PraiseComment.java
  src/main/java/org/example/hugmeexp/domain/praise/exception/CommentNotFoundException.java
  src/main/java/org/example/hugmeexp/domain/praise/mapper/CommentMapper.java
  src/main/java/org/example/hugmeexp/domain/praise/service/CommentService.java
Labels: 기능 개발

#83 Feature/#74 미션 제출 및 피드백 기능 구현
  src/main/java/org/example/hugmeexp/domain/mission/controller/ChallengeController.java
  src/main/java/org/example/hugmeexp/domain/mission/controller/SubmissionController.java
  src/main/java/org/example/hugmeexp/domain/mission/dto/request/SubmissionFeedbackRequest.java
  src/main/java/org/example/hugmeexp/domain/mission/dto/request/SubmissionUploadRequest.java
  src/main/java/org/example/hugmeexp/domain/mission/dto/response/SubmissionResponse.java
  src/main/java/org/example/hugmeexp/domain/mission/entity/Submission.java
  src/main/java/org/example/hugmeexp/domain/mission/exception/AlreadyExistsUserMissionSubmissionException.java
  src/main/java/org/example/hugmeexp/domain/mission/exception/SubMissionInternalException.java
  src/main/java/org/example/hugmeexp/domain/mission/exception/SubmissionFileUploadException.java
  src/main/java/org/example/hugmeexp/domain/mission/exception/SubmissionNotFoundException.java
  src/main/java/org/example/hugmeexp/domain/mission/mapper/UserMissionSubmissionMapper.java
  src/main/java/org/example/hugmeexp/domain/mission/repository/UserMissionSubmissionRepository.java
  src/main/java/org/example/hugmeexp/domain/mission/service/MissionService.java
  src/main/java/org/example/hugmeexp/domain/mission/service/MissionServiceImpl.java
  src/main/java/org/example/hugmeexp/global/common/exception/ExceptionController.java
  src/test/java/org/example/hugmeexp/domain/mission/controller/ChallengeControllerTest.java
  src/test/java/org/example/hugmeexp/domain/mission/service/MissionServiceTest.java
Labels: 기능 개발

#88 댓글 삭제 기능
  src/main/java/org/example/hugmeexp/domain/praise/controller/CommentController.java
  src/main/java/org/example/hugmeexp/domain/praise/exception/ForbiddenCommentAccessException.java
  src/main/java/org/example/hugmeexp/domain/praise/service/CommentService.java
  src/main/java/org/example/hugmeexp/domain/praise/service/PraiseService.java
Labels: 기능 개발

#94 출석체크 전체적인 리팩토링, service 전면 교체 (테스트코드 미완료)
  src/main/java/org/example/hugmeexp/domain/attendance.zip
  src/main/java/org/example/hugmeexp/domain/attendance/controller/AttendanceController.java
  src/main/java/org/example/hugmeexp/domain/attendance/dto/AttendanceCheckRequest.java
  src/main/java/org/example/hugmeexp/domain/attendance/dto/AttendanceCheckResponse.java
  src/main/java/org/example/hugmeexp/domain/attendance/dto/AttendanceStatusResponse.java
  src/main/java/org/example/hugmeexp/domain/attendance/entity/Attendance.java
  src/main/java/org/example/hugmeexp/domain/attendance/exception/AttendanceAlreadyCheckedException.java
  src/main/java/org/example/hugmeexp/domain/attendance/exception/AttendanceUserNotFoundException.java
  src/main/java/org/example/hugmeexp/domain/attendance/policy/RewardPolicy.java
  src/main/java/org/example/hugmeexp/domain/attendance/repository/AttendanceRepository.java
  src/main/java/org/example/hugmeexp/domain/attendance/service/AttendanceService.java
  src/main/java/org/example/hugmeexp/global/common/exception.zip
Labels: 기능 개발

#97 칭찬 게시물 반응 삭제
  src/main/java/org/example/hugmeexp/domain/praise/controller/CommentController.java
  src/main/java/org/example/hugmeexp/domain/praise/controller/PraiseEmojiReactionController.java
  src/main/java/org/example/hugmeexp/domain/praise/exception/InvalidPraiseEmojiAccessException.java
  src/main/java/org/example/hugmeexp/domain/praise/exception/PraiseEmojiReactionNotFoundException.java
  src/main/java/org/example/hugmeexp/domain/praise/exception/UnauthorizedEmojiDeleteException.java
  src/main/java/org/example/hugmeexp/domain/praise/repository/PraiseEmojiReactionRepository.java
  src/main/java/org/example/hugmeexp/domain/praise/service/PraiseEmojiReactionService.java
Labels: 기능 개발

#100 Feature/#99 미션 제출 업로드 경로 변경
  .gitignore
  src/main/java/org/example/hugmeexp/domain/mission/controller/SubmissionController.java
  src/main/java/org/example/hugmeexp/domain/mission/enums/FileUploadType.java
  src/main/java/org/example/hugmeexp/domain/mission/service/MissionServiceImpl.java
  src/main/java/org/example/hugmeexp/domain/mission/util/FileUploadUtils.java
  src/test/java/org/example/hugmeexp/domain/mission/service/MissionServiceTest.java
Labels: 기능 개발

#106 칭찬 댓글 반응 삭제 기능 구현
  src/main/java/org/example/hugmeexp/domain/praise/controller/CommentEmojiReactionController.java
  src/main/java/org/example/hugmeexp/domain/praise/exception/CommentEmojiReactionNotFoundException.java
  src/main/java/org/example/hugmeexp/domain/praise/exception/MismatchedCommentReactionException.java
  src/main/java/org/example/hugmeexp/domain/praise/service/CommentEmojiReactionService.java
Labels: 기능 개발

#114 칭찬 게시물 댓글 조회 기능 구현
  src/main/java/org/example/hugmeexp/domain/praise/repository/CommentRepository.java
Labels: 기능 개발

#117 Bugfix/#116 출석체크 기능 실행 가능한 상태로 수정
  src/main/java/org/example/hugmeexp/domain/attendance/service/AttendanceService.java
  src/test/java/org/example/hugmeexp/domain/attendance/controller/AttendanceControllerTest.java
  src/test/java/org/example/hugmeexp/domain/attendance/service/AttendanceServiceTest.java
Labels: 버그

#123 bugfix: Mission, MissionGroup 테스트 UserProfileResponse 파라미터 버그 수정
  src/test/java/org/example/hugmeexp/domain/missionGroup/controller/MissionGroupControllerTest.java
  src/test/java/org/example/hugmeexp/domain/missionGroup/service/MissionGroupServiceTest.java
Labels: 버그

#130 feat: 미션 태스크 관리 기능 추가
  src/main/java/org/example/hugmeexp/domain/mission/controller/MissionController.java
  src/main/java/org/example/hugmeexp/domain/mission/repository/UserMissionRepository.java
  src/main/java/org/example/hugmeexp/domain/missionTask/controller/MissionTaskController.java
  src/main/java/org/example/hugmeexp/domain/missionTask/dto/request/MissionTaskRequest.java
  src/main/java/org/example/hugmeexp/domain/missionTask/dto/response/MissionTaskResponse.java
  src/main/java/org/example/hugmeexp/domain/missionTask/dto/response/UserMissionTaskResponse.java
  src/main/java/org/example/hugmeexp/domain/missionTask/entity/MissionTask.java
  src/main/java/org/example/hugmeexp/domain/missionTask/entity/UserMissionTask.java
  src/main/java/org/example/hugmeexp/domain/missionTask/enums/TaskState.java
  src/main/java/org/example/hugmeexp/domain/missionTask/exception/MissionTaskNotFoundException.java
  src/main/java/org/example/hugmeexp/domain/missionTask/mapper/MissionTaskMapper.java
  src/main/java/org/example/hugmeexp/domain/missionTask/repository/MissionTaskRepository.java
  src/main/java/org/example/hugmeexp/domain/missionTask/repository/UserMissionTaskRepository.java
  src/main/java/org/example/hugmeexp/domain/missionTask/service/MissionTaskService.java
  src/main/java/org/example/hugmeexp/domain/missionTask/service/MissionTaskServiceImpl.java
Labels: 기능 개발

#132 feat: 미션 그룹 사용자 목록 조회 API 추가
  src/main/java/org/example/hugmeexp/domain/missionGroup/controller/MissionGroupController.java
  src/main/java/org/example/hugmeexp/domain/missionGroup/repository/UserMissionGroupRepository.java
  src/main/java/org/example/hugmeexp/domain/missionGroup/service/MissionGroupService.java
  src/main/java/org/example/hugmeexp/domain/missionGroup/service/MissionGroupServiceImpl.java
Labels: 기능 개발

#137 칭찬 게시물 반응 관련기능 수정
  src/main/java/org/example/hugmeexp/domain/praise/dto/EmojiReactionGroupDTO.java
  src/main/java/org/example/hugmeexp/domain/praise/dto/PraiseEmojiReactionResponseDTO.java
  src/main/java/org/example/hugmeexp/domain/praise/dto/ReactionUserDTO.java
Labels: 성능 개선

#141 출석체크 도메인 전면 리팩토링 & 테스트 코드 작성
  src/main/java/org/example/hugmeexp/domain/attendance/controller/AttendanceController.java
  src/main/java/org/example/hugmeexp/domain/attendance/dto/AttendanceCheckRequest.java
  src/main/java/org/example/hugmeexp/domain/attendance/dto/AttendanceCheckResponse.java
  src/main/java/org/example/hugmeexp/domain/attendance/entity/Attendance.java
  src/main/java/org/example/hugmeexp/domain/attendance/exception/InvalidValueException.java
  src/main/java/org/example/hugmeexp/domain/attendance/exception/UsernameTooLongException.java
  src/main/java/org/example/hugmeexp/domain/attendance/policy/RewardPolicy.java
  src/main/java/org/example/hugmeexp/domain/attendance/repository/AttendanceRepository.java
  src/main/java/org/example/hugmeexp/domain/attendance/service/AttendanceService.java
  src/main/java/org/example/hugmeexp/domain/qeust/validator/AttendanceValidator.java
  src/test/java/org/example/hugmeexp/domain/attendance/controller/AttendanceControllerTest.java
  src/test/java/org/example/hugmeexp/domain/attendance/service/AttendanceServiceTest.java
Labels: 기능 개발, 버그

#151 출석체크 도메인: db 유니크 제약 추가, 낙관적 락 삭제 #
  src/main/java/org/example/hugmeexp/domain/attendance/controller/AttendanceController.java
  src/main/java/org/example/hugmeexp/domain/attendance/dto/AttendanceCheckRequest.java
  src/main/java/org/example/hugmeexp/domain/attendance/entity/Attendance.java
  src/main/java/org/example/hugmeexp/domain/attendance/exception/InvalidValueException.java
  src/main/java/org/example/hugmeexp/domain/attendance/exception/UsernameTooLongException.java
  src/main/java/org/example/hugmeexp/domain/attendance/service/AttendanceService.java
Labels: 버그

#152 Feature/#146 유저 미션 API에 빠진 API 추가
  src/main/java/org/example/hugmeexp/domain/mission/controller/ChallengeController.java
  src/main/java/org/example/hugmeexp/domain/mission/controller/MissionController.java
  src/main/java/org/example/hugmeexp/domain/mission/mapper/UserMissionMapper.java
  src/main/java/org/example/hugmeexp/domain/mission/mapper/UserMissionSubmissionMapper.java
  src/main/java/org/example/hugmeexp/domain/mission/repository/UserMissionRepository.java
  src/main/java/org/example/hugmeexp/domain/mission/service/MissionService.java
  src/main/java/org/example/hugmeexp/domain/mission/service/MissionServiceImpl.java
Labels: 기능 개발, 버그

#145 칭찬 댓글 반응 관련 기능 수정
  src/main/java/org/example/hugmeexp/domain/praise/controller/CommentEmojiReactionController.java
  src/main/java/org/example/hugmeexp/domain/praise/dto/CommentEmojiReactionResponseDTO.java
  src/main/java/org/example/hugmeexp/domain/praise/dto/CommentResponseDTO.java
  src/main/java/org/example/hugmeexp/domain/praise/dto/PraiseDetailResponseDTO.java
  src/main/java/org/example/hugmeexp/domain/praise/mapper/CommentEmojiReactionMapper.java
  src/main/java/org/example/hugmeexp/domain/praise/repository/CommentEmojiReactionRepository.java
  src/main/java/org/example/hugmeexp/domain/praise/service/CommentEmojiReactionService.java
  src/main/java/org/example/hugmeexp/domain/praise/service/CommentService.java
  src/main/java/org/example/hugmeexp/domain/praise/service/PraiseService.java
Labels: 기능 개발

#155 출석체크 도메인 불필요한 테스트 제거
  src/test/java/org/example/hugmeexp/domain/attendance/service/AttendanceServiceTest.java
Labels: 버그

#158 북마크 구현
  docker-compose.yml
  src/main/java/org/example/hugmeexp/domain/bookmark/controller/BookmarkController.java
  src/main/java/org/example/hugmeexp/domain/bookmark/dto/BookmarkRequest.java
  src/main/java/org/example/hugmeexp/domain/bookmark/dto/BookmarkResponse.java
  src/main/java/org/example/hugmeexp/domain/bookmark/entity/Bookmark.java
  src/main/java/org/example/hugmeexp/domain/bookmark/exception/BookmarkNotFoundException.java
  src/main/java/org/example/hugmeexp/domain/bookmark/exception/BookmarkUserNotFoundException.java
  src/main/java/org/example/hugmeexp/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/org/example/hugmeexp/domain/bookmark/service/BookmarkService.java
Labels: 기능 개발

#169 북마크 도메인 swagger 추가
  src/main/java/org/example/hugmeexp/domain/bookmark/controller/BookmarkController.java
  src/main/java/org/example/hugmeexp/domain/bookmark/dto/BookmarkRequest.java
  src/main/java/org/example/hugmeexp/domain/bookmark/dto/BookmarkResponse.java
Labels: 기능 개발

#168 츨석체크 도메인 swagger 추가
  src/main/java/org/example/hugmeexp/domain/attendance/controller/AttendanceController.java
  src/main/java/org/example/hugmeexp/domain/attendance/dto/AttendanceCheckResponse.java
  src/main/java/org/example/hugmeexp/domain/attendance/dto/AttendanceStatusResponse.java
Labels: 기능 개발
